### ISSUE TITLE
Guice creation errors

### ISSUE THREAD

**Issue by bquisling** [Netflix/Raigad#32]
When attempting to run the latest raigad-web, I am encountering the following problem when deploying Raiged.war:

```
14 errors
com.google.inject.CreationException: Guice creation errors:

1) Error injecting constructor, java.lang.NullPointerException
  at com.netflix.raigad.configuration.RaigadConfiguration.<init>(RaigadConfiguration.java:299)
  at com.netflix.raigad.configuration.RaigadConfiguration.class(RaigadConfiguration.java:36)
  while locating com.netflix.raigad.configuration.RaigadConfiguration
  while locating com.netflix.raigad.configuration.IConfiguration
    for field at com.netflix.raigad.identity.CassandraInstanceFactory.config(CassandraInstanceFactory.java:30)
  at com.netflix.raigad.identity.CassandraInstanceFactory.class(CassandraInstanceFactory.java:30)
  while locating com.netflix.raigad.identity.CassandraInstanceFactory
  while locating com.netflix.raigad.identity.IRaigadInstanceFactory
Caused by: java.lang.NullPointerException
	at com.netflix.raigad.configuration.RaigadConfiguration.getDefaultCredentialProvider(RaigadConfiguration.java:853)
	at com.netflix.raigad.configuration.RaigadConfiguration.<init>(RaigadConfiguration.java:221)
	at com.netflix.raigad.configuration.RaigadConfiguration$$FastClassByGuice$$a6937af9.newInstance(<generated>)
	at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
```

The issue appears to be due to the code on line 221 (and the similar initializations below that):
```java
private final DynamicStringProperty CREDENTIAL_PROVIDER = DynamicPropertyFactory.getInstance().getStringProperty(CONFIG_CREDENTIAL_PROVIDER, getDefaultCredentialProvider());
```
This code seems to get executed before the constructor initializes the config field with the injected IConfigSource. I have debugged the dependency injection and it does appear that the injector has indeed located an instance of the default RaigadConfigSource and has passed it to the RaigadConfiguration constructor. So if the code on line 221 was evaluated after the class construction things would be fine. But this appears to happen out of order, hence the NPE.

Any ideas what I'm doing wrong or if this is a known issue?

**Comment by bquisling** [comment]
I can work around this issue by moving the code around something like this:
```java
    @Inject
    public RaigadConfiguration(ICredential provider, IConfigSource config)
    {
        this.provider = provider;
        this.config = config;
        initializeProps();
    }

    private void initializeProps() {
        CREDENTIAL_PROVIDER = DynamicPropertyFactory.getInstance().getStringProperty(CONFIG_CREDENTIAL_PROVIDER, getDefaultCredentialProvider());
        ES_STARTUP_SCRIPT_LOCATION = DynamicPropertyFactory.getInstance().getStringProperty(CONFIG_ES_START_SCRIPT, getDefaultEsStartScript());
```
I would like to avoid having to do this if possible -

**Comment by sagarl** [comment]
@bquisling I'll get back to you on this. Currently tackling few prod issues.

**Comment by sagarl** [comment]
Fixed with https://github.com/Netflix/Raigad/pull/41

Let me know if you are still facing the issues.
